name: Saatlik SEO Guncelleme

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

# Bu kısım uyarıyı susturur ve sistemi Node.js 24'e zorlar
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
      - name: Depoyu Kontrol Et
        uses: actions/checkout@v4 # v4 en güncel sürümdür

      - name: Python'ı Kur
        uses: actions/setup-python@v5 # v4'ten v5'e yükselttik (Node 24 uyumu için)
        with:
          python-version: '3.11'

      - name: Gereksinimleri Yukle
        run: |
          pip install -r requirements.txt

      - name: Python Betigini Calistir
        run: python seo_saldiri.py

      - name: Netlify'a Yükle
        uses: nwtgck/actions-netlify@v3.0 # v2'den v3'e güncelledik
        with:
          publish-dir: './' 
          production-deploy: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ https://ferzan-ozpetek-archive.netlify.app }}
